# Generated by Django 4.2.16 on 2024-10-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing_app', '0003_vqi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='image',
        ),
        migrations.DeleteModel(
            name='PDF',
        ),
        migrations.AddField(
            model_name='vqi',
            name='colourfulness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vqi',
            name='doc_filename',
            field=models.CharField(default='default_doc_filename', max_length=255),
        ),
        migrations.AddField(
            model_name='vqi',
            name='doc_headline',
            field=models.TextField(default='default_doc_headline'),
        ),
        migrations.AddField(
            model_name='vqi',
            name='doc_url',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AddField(
            model_name='vqi',
            name='vqis_filename',
            field=models.CharField(default='default_vqis_filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='blackout',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='blockiness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='blockloss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='blur',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='contrast',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='exposure_bri',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='flickering',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='frame',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='freezing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='interlace',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='letterbox',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='noise',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='pillarbox',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='sa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='slice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vqi',
            name='ta',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
    ]
