# Generated by Django 4.2.16 on 2024-10-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing_app', '0004_remove_indicator_image_delete_pdf_vqi_colourfulness_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VQI',
            new_name='VideoQualityMetrics',
        ),
    ]
