version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
    volumes:
      - .:/app
      - ./media:/app/app/media  # Map the host's ./media directory to the container's /app/media directory
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data: