services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
    volumes:
      - ./data:/data
      - ./media:/app/media
      - "C:/Users/jakub_lk/OneDrive/.inżynierka/image_processing:/app"
      - "C:/Users/jakub_lk/OneDrive/.inżynierka/data1:/app/data"
      - "C:/Users/jakub_lk/OneDrive/.inżynierka/Es_pdfs(Art2)/From 2023-01-01 to 2023-01-31_3724PDFs_pictures:/app/images"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  postgres_data:
